apiVersion: carto.run/v1alpha1
kind: ClusterSourceTemplate
metadata:
  name: source
spec:
  urlPath: .status.artifact.url
  revisionPath: .status.artifact.revision

  template:
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: GitRepository
    metadata:
      name: hello-world
    spec:
      interval: 1m0s
      url: https://github.com/ciberkleid/hello-go
      ref:
        branch: main
      gitImplementation: libgit2
      ignore: ""
